[package]
name = "mpm"
version = "0.3.1"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
strum = { version = "0.26", features = ["derive"] }
tabled = { version = "0.15", features = ["color"] }

[features]
default = ["verify"]
verify = []
